### PR TITLE
[#172] Update default factory class to current CI

### LINKED ISSUE #172: Should JAXB 3.0's ModuleUtil be referring to "com.sun.xml.internal.bind.v2.ContextFactory" RI class?
When pulling in the JAXB 3.0 implementation in Open Liberty, we ran into an issue where the ModuleUtil file still references the old `com.sun.xml.internal.bind.v2.ContextFactory` reference implementation (see https://github.com/eclipse-ee4j/jaxb-api/blob/b717e34080470d12dfdd2daf74c3100dddae7c2b/jaxb-api/src/main/java/jakarta/xml/bind/ModuleUtil.java#L37 ).  I believe that it should be referencing `org.glassfish.jaxb.runtime.v2.ContextFactory` instead.

If this was an oversight in the 3.0 release, I would be happy to update the classname in ModuleUtil.  In that case would it be possible to publish a 3.0.1 release that includes this change?  Thanks!

### PR DESCRIPTION
**Pull request by andymc12**
Fixes #172.

### CODE REVIEW

**Review by lukasj — CHANGES_REQUESTED** [review]
This change is tempting, isn't it? :-)

While it might not be necessarily wrong, I have few problems with this, at least with its current form...

* is it needed to have one constant having the same value defined on multiple places where one is there to cover JDK 8 and the other JDK 11+?

* what is the real problem you are trying to solve here? In the other words - the API should be able to find an implementation on the classpath or module path and fallback to the reflection as the last resort. Reflection assumes that the to be created class is available on the classpath or module path but if such class is really on the classpath/modulepath then why it has not been found and instantiated by previous steps avoiding reflection call/fallback to the "default"? Do you see the cycle as I do here? Am I missing something?

* what are xjc and schemagen commands coming with the default CI (or jaxb-compiler from moxy) doing differently so they are able to be properly loaded and working on both - JDK 8 as well as on JDK 11+?

**Comment by andymc12** [comment]
Hi @lukasj

> is it needed to have one constant having the same value defined on multiple places where one is there to cover JDK 8 and the other JDK 11+?

I believe so.  The JDK used to provide the "com.sun" classes in JDK 8, but those are incompatible with Jakarta XML Binding in EE 9 due to the package name changes.  So regardless which JVM a user is running in, they will need an impl that supports the `jakarta.xml.bind` package.  

> what is the real problem you are trying to solve here? In the other words - the API should be able to find an implementation on the classpath or module path and fallback to the reflection as the last resort. Reflection assumes that the to be created class is available on the classpath or module path but if such class is really on the classpath/modulepath then why it has not been found and instantiated by previous steps avoiding reflection call/fallback to the "default"? Do you see the cycle as I do here? Am I missing something?

I think the main problem is seen in OSGi environments where finding META-INF/services files in other bundles is not trivial. Also, in Open Liberty, we want to allow users to be able to specify their own impl (via META-INF/services file in their application) if they want to, but otherwise depend on the system default.  With parent-first (default) classloading rules, if Liberty provided the default via META-INF/services, then the system default would always be selected.  This is effectively a change in behavior from EE8 (where users could provide their own JAXB impl) to EE9 (where they are stuck with the system default - unless they workaround it with classloading tricks).

The other problem with it is architectural purity.  The current fallback impl ("com.sun...") doesn't actually implement the API, so it will never work as a fallback.  Best case, this is dead code.  Worst case, you get classloading issues like @Siedlerchr and I are seeing.

> what are xjc and schemagen commands coming with the default CI (or jaxb-compiler from moxy) doing differently so they are able to be properly loaded and working on both - JDK 8 as well as on JDK 11+?

I haven't investigated this properly, but my guess is that these tools (1) run in a Java SE environment (or a non-OSGi Java EE environment) and (2) provide a proper implementation using META-INF/services.

Thanks for taking a look at this.

**Comment by Siedlerchr** [comment]
We are using xjc with ant + gradle and we are also getting this error:  It's still searching for this com.sun.xml.bind.v2.ContextFactory:

```
   implementation group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: '3.0.0'
    implementation group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: '3.0.0'
    xjc group: 'org.glassfish.jaxb', name: 'jaxb-xjc', version: '3.0.0'
```
Execution failed for task ':generateBibtexmlSource'.
> java.lang.AssertionError: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
   - with linked exception:
  [java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]

**Comment by lukasj** [comment]
> Hi @lukasj
> 
> > is it needed to have one constant having the same value defined on multiple places where one is there to cover JDK 8 and the other JDK 11+?
> 
> I believe so. The JDK used to provide the "com.sun" classes in JDK 8, but those are incompatible with Jakarta XML Binding in EE 9 due to the package name changes. So regardless which JVM a user is running in, they will need an impl that supports the `jakarta.xml.bind` package.

so? With your change, one ends up with a jar having following definitions:

```
bind-api.jar/jakarta/xml/bind/ModuleUtil.class - DEFAULT_FACTORY_CLASS = "org.glassfish.jaxb.runtime.v2.ContextFactory".toString()
bind-api.jar/META-INF/versions/9/jakarta/xml/bind/ModuleUtil.class - DEFAULT_FACTORY_CLASS = "org.glassfish.jaxb.runtime.v2.ContextFactory".toString()
```

Why is it required to have the same value defined twice in the current Jakarta EE 9+ context? IMHO it is enough to _change_ first occurrence, remove `toString()` call on it to allow compiler inlining and _completely delete_ second definition of the constant. Basically "rollback" changes in this area to EE 7 state

> I think the main problem is seen in OSGi environments where finding META-INF/services files in other bundles is not trivial. 

Agree, OSGi is hell :-/ But why it works properly (or at least it is pretending it works properly) in GF, which is built on top of OSGi too? Also note that there exists https://github.com/eclipse-ee4j/saaj-api/issues/43 suggesting supporting OSGi ServiceLoader mediator standard - would that be way to go forward?

Would it be possible to come up with some test for your scenario? I've found pax-exam useful for this kind of tests in the past.

> [...] This is effectively a change in behavior from EE8 (where users could provide their own JAXB impl) to EE9 (where they are stuck with the system default - unless they workaround it with classloading tricks).

the main cause here is removal of jaxb from JDK, so there is no Java SE default one can fallback to and jaxb-ri as such should be treated as "another" implementation, since as you have pointed out, one wants this as default while the other one wants that as default.

> 
> The other problem with it is architectural purity. The current fallback impl ("com.sun...") doesn't actually implement the API, so it will never work as a fallback. Best case, this is dead code. Worst case, you get classloading issues like @Siedlerchr and I are seeing.

Yes, I agree it is a dead code. At least for now.

> 
> > what are xjc and schemagen commands coming with the default CI (or jaxb-compiler from moxy) doing differently so they are able to be properly loaded and working on both - JDK 8 as well as on JDK 11+?
> 
> I haven't investigated this properly, but my guess is that these tools (1) run in a Java SE environment (or a non-OSGi Java EE environment) and (2) provide a proper implementation using META-INF/services.
> 

yes, they are SE tools running also with EE container. I was hoping it can be some cp issue.

**Comment by lukasj** [comment]
> We are using xjc with ant + gradle and we are also getting this error: JDK15
> It's still searching for this com.sun.xml.bind.v2.ContextFactory:
> 
> ```
>    implementation group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: '3.0.0'
>     implementation group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: '3.0.0'
>     xjc group: 'org.glassfish.jaxb', name: 'jaxb-xjc', version: '3.0.0'
> ```
> 
> Execution failed for task ':generateBibtexmlSource'.
> 
> > java.lang.AssertionError: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
> 
> * with linked exception:
>   [java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]

have you tried to use `com.sun.xml.bind:jaxb-xjc` instead? is gradle putting libraries on the classpath or on the module path? what is exact command line invoked by gradle?

**Comment by Siedlerchr** [comment]
@lukasj  I provided a debug log from the gradle task: https://nopaste.xyz/?4f473486b13f0b80#2LSg1AHYjtnbN6QGXEhPdfnKPMHpQPKr2UYovuWhjZri

There you can exactly see where the ant class loading fails

This time I tried with com.sun.xml

And if you want to reproduce  it:
https://github.com/JabRef/jabref/pull/7161
`./gradlew generateSource ` calls the ant task.

**Comment by lukasj** [comment]
@Siedlerchr try with either these  dependencies:
```
jakarta.xml.bind:jakarta.xml.bind-api:3.0.0
com.sun.xml.bind:jaxb-xjc:3.0.0
com.sun.xml.bind:jaxb-core:3.0.0
com.sun.xml.bind:jaxb-impl:3.0.0
```

or if you want to try MOXy instead:
```
jakarta.xml.bind:jakarta.xml.bind-api:3.0.0
com.sun.xml.bind:jaxb-xjc:3.0.0
com.sun.xml.bind:jaxb-core:3.0.0
org.eclipse.persistence:org.eclipse.persistence.moxy:3.0.0-RC1
```

and remove everything with "org.glassfish.jaxb" prefix

**Comment by Siedlerchr** [comment]
Thanks, the first combination worked!
I had to put the impl to the xjc configuraiton
`xjc group: 'com.sun.xml.bind', name: 'jaxb-impl', version: '3.0.0'`

**Comment by lukasj** [comment]
covered in #176 (basically cleans this one up a bit)

**Pull request closed without merging**
