### PR TITLE
xmlb-12,  xmlb-13,  xmlb-8 and xmlb-25 are recreated in SVG format.  xmlb-15 is recreated in PNG format.

### PR DESCRIPTION
**Pull request by DmitriGit**
Done.

Three images are missing to convert now. Hope tomorrow commit these three images.

Dmitri.

### CODE REVIEW

**Comment by DmitriGit** [comment]
All images are recreated. 

Now you have a very nice Specification. :)

Dmitri.

**Review by lukasj — COMMENTED** [review]
can the text in "built-in primitive types" be in white (or colors be changed/updated) so it becomes readable? Having black text on the black background can be challenging to read in the dark room in the evening :-) The most readable version of the picture I've found is in the version 2 of the original spec at https://download.oracle.com/otndocs/jcp/jaxb-2.0-fr-eval-oth-JSpec/

**Comment by DmitriGit** [comment]
:)))) I'm very sorry, Lukas!!! 

Don't know how I commited a picture like this! :))
Sorry...

Tomorrow you'll have a picture in SVG format and we are OK. :)

Dmitri.

**Comment by DmitriGit** [comment]
Look my commit 1 minute ago. Tell me, please, if that version is OK.

Dmitri.

**Review by lukasj — APPROVED** [review]
Yes, this is it! Thanks a lot!
LGTM

**Comment by DmitriGit** [comment]
Ok, I'm happy!

:)

**Pull request merged**
