### PR TITLE
Prevent Java Compiler inlining of default ModuleUtil.DEFAULT_FACTORY_CLASS

### PR DESCRIPTION
**Pull request by vladimirfx**
Fix for https://github.com/eclipse-ee4j/jaxb-api/issues/78

### CODE REVIEW

**Comment by bravehorsie** [comment]
@vladimirfx Thank you for the fix! You need to sign an ECA contributor agreement in order to contribute and sign off the commit.

**Comment by vladimirfx** [comment]
> @vladimirfx Thank you for the fix! You need to sign an ECA contributor agreement in order to contribute and sign off the commit.

I've tryed - Eclipse Account do not activated. Can't sign in.

**Comment by bravehorsie** [comment]
Can't accept without it unfortunately, every contributor has signed it so far.

**Comment by vladimirfx** [comment]
I've signed ECA

**Comment by lukasj** [comment]
this should have been merged to MASTER and not EE4J branch... :-/

**Comment by vladimirfx** [comment]
> this should have been merged to MASTER and not EE4J_8 branch... :-/

Original fix attempt was made in EE4J_8 so my fix is based on it.

**Pull request merged**
